Add prettier format pre-commit hook, improve scripts and remove format Makefile targets

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -1,18 +1,17 @@
-#!/usr/bin/env bash
+#!/bin/sh
+# Forces the commit message to be in a certain format
 
-red=$'\033[31m'
-green=$'\033[32m'
-rst=$'\033[m'
+set -eu
+
+die () {
+	printf '\033[31mError: %s\033[m\n' "${1:-"Script $0 exited with unknown error"}"
+	exit 1
+}
 
 regex_titlecase_verb='^[A-Z][a-z]+ '
 regex_imperative_verb='^[A-Z][a-z]+ed '
-error_msg1="${red}Commit message format is incorrect (must start with titlecase verb, regex: '^[A-Z][a-z]+ '). Example: '${green}Add feature${rst}${red}' or '${green}Update file${rst}${red}'${rst}."
-error_msg2="${red}Commit message format is incorrect (use imperative verb form). Example: '${green}Add feature${rst}${red}' or '${green}Update file${rst}${red}'${rst}."
 
-if ! grep -qE -e "$regex_titlecase_verb" "$1" ; then
-    echo "$error_msg1" >&2
-    exit 1
-elif grep -qE -e "$regex_imperative_verb" "$1" ; then
-    echo "$error_msg2" >&2
-    exit 2
-fi
+grep -qE -e "$regex_titlecase_verb" -- "$1" || \
+	die "Error: Commit message format is incorrect (must start with titlecase verb). Example: 'Add feature' or 'Update file'"
+grep -qE -e "$regex_imperative_verb" "$1" && \
+	die "Error: Commit message format is incorrect (use imperative verb form). Example: 'Add feature' or 'Update file'"
diff --git a/.githooks/disable-hooks b/.githooks/disable-hooks
--- a/.githooks/disable-hooks
+++ b/.githooks/disable-hooks
@@ -1,7 +1,14 @@
 #!/bin/sh
+# Resets the hooks path to the default, which will disable all hooks in this directory
+
+set -eu
+
+die () {
+	printf '\033[31mError: %s\033[m\n' "${1:-"Script $0 exited with unknown error"}"
+	exit 1
+}
 
 git_path=$(git rev-parse --show-toplevel) || { echo "You're not in a git repo, can't reset hooks"; exit 1; }
-hooks_path=.githooks/
 
 printf 'You are in this repository: %s\n' "$git_path"
 printf 'And the hooks path will be reset\n'
@@ -10,6 +17,6 @@ read -r choice
 choice=$(printf %s "$choice" | tr Y y | xargs)
 [ "$choice" = y ] || [ -z "$choice" ] || { echo "Will not reset hooks path"; exit 2; }
 
-git config --local --unset core.hooksPath
+git config --local --unset core.hooksPath || die "Failed to reset hooks path"
 
 echo "Hooks path was reset"
diff --git a/.githooks/enable-hooks b/.githooks/enable-hooks
--- a/.githooks/enable-hooks
+++ b/.githooks/enable-hooks
@@ -1,4 +1,12 @@
 #!/bin/sh
+# Sets the hooks path, which will enable all hooks in this directory
+
+set -eu
+
+die () {
+	printf '\033[31mError: %s\033[m\n' "${1:-"Script $0 exited with unknown error"}"
+	exit 1
+}
 
 git_path=$(git rev-parse --show-toplevel) || { echo "You're not in a git repo, can't enable hooks"; exit 1; }
 hooks_path=.githooks/
@@ -10,6 +18,6 @@ read -r choice
 choice=$(printf %s "$choice" | tr Y y | xargs)
 [ "$choice" = y ] || [ -z "$choice" ] || { echo "Will not update hooks path"; exit 2; }
 
-git config --local core.hooksPath "$hooks_path"
+git config --local core.hooksPath "$hooks_path" || die "Failed to set hooks path"
 
 echo "Hooks path was updated"
